#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15

    environment:
      JOBS: max # https://gist.github.com/ralphtheninja/f7c45bdee00784b41fed

    working_directory: ~/zmi

    steps:
      - checkout
      - run: yarn
      - run: yarn zmi-nerd
      - run: yarn zmi-bootstrap
      - run: yarn test --forceExit --detectOpenHandles --runInBand --maxWorkers=2
      - run: bash <(curl -s https://codecov.io/bash)
