# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    paths-ignore:
      - '.github/workflows/docs.yml'
      - '.github/**/*.md'
      - '.circleci/**'
      - 'examples/**'
      - 'website/**'
      - 'docs/**'
      - '*.md'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.13.0, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup restore
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Setup install
        if: ${{ steps.cache.outputs.cache-hit != true }}
        run: yarn --ignore-engines
      - run: yarn zmi-nerd
      - run: yarn test --forceExit
        env:
          NODE_ENV: test
          CI: true
